# Generated by Django 3.1 on 2022-06-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbusto',
            fields=[
                ('idArbusto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Arbusto')),
                ('nombreArbusto', models.CharField(max_length=50, verbose_name='Nombre de Arbusto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombreCompleto', models.CharField(max_length=200, verbose_name='Nombre de Cliente')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('contrasena', models.CharField(max_length=20, verbose_name='Contraseña de Cliente')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('comentario', models.TextField(verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('idFlor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de flor')),
                ('nombreFlor', models.CharField(max_length=50, verbose_name='Nombre de Flor')),
            ],
        ),
        migrations.CreateModel(
            name='Macetero',
            fields=[
                ('idMacetero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de macetero')),
                ('colorMacetero', models.CharField(max_length=50, verbose_name='Color de Macetero')),
            ],
        ),
        migrations.CreateModel(
            name='Sustrato',
            fields=[
                ('idSustrato', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de sustrato')),
                ('tipoSustrato', models.CharField(max_length=50, verbose_name='Tipo de Macetero')),
            ],
        ),
    ]
