# Generated by Django 3.1 on 2022-07-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbusto',
            fields=[
                ('idArbusto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Arbusto')),
                ('nombreArbusto', models.CharField(max_length=50, verbose_name='Nombre de Arbusto')),
                ('stockArbusto', models.IntegerField(default=0, verbose_name='Stock de Arbusto')),
                ('precioArbusto', models.IntegerField(default=0, verbose_name='Precio de Arbusto')),
                ('imagenArbusto', models.CharField(max_length=300, verbose_name='Imagen Arbusto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombreCompleto', models.CharField(max_length=200, verbose_name='Nombre de Cliente')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('contrasena', models.CharField(max_length=20, verbose_name='Contraseña de Cliente')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('direccion', models.CharField(default=False, max_length=300, verbose_name='Dirección')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('ultimaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('idFlor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de flor')),
                ('nombreFlor', models.CharField(max_length=50, verbose_name='Nombre de Flor')),
                ('stockFlor', models.IntegerField(default=0, verbose_name='Stock de Flor')),
                ('precioFlor', models.IntegerField(default=0, verbose_name='Precio de Flor')),
                ('imagenFlor', models.CharField(max_length=300, verbose_name='Imagen flor')),
            ],
        ),
        migrations.CreateModel(
            name='Macetero',
            fields=[
                ('idMacetero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de macetero')),
                ('colorMacetero', models.CharField(max_length=50, verbose_name='Color de Macetero')),
                ('stockMacetero', models.IntegerField(default=0, verbose_name='Stock de Macetero')),
                ('precioMacetero', models.IntegerField(default=0, verbose_name='Precio de Macetero')),
                ('imagenMacetero', models.CharField(max_length=300, verbose_name='Imagen Macetero')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombreProducto', models.CharField(max_length=200, verbose_name='Nombre Producto')),
                ('tipoProducto', models.CharField(max_length=200, verbose_name='Tipo Producto')),
                ('precioProducto', models.FloatField()),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('imagenProducto', models.CharField(max_length=300, verbose_name='Imagen Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Sustrato',
            fields=[
                ('idSustrato', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de sustrato')),
                ('tipoSustrato', models.CharField(max_length=50, verbose_name='Tipo de Sustrato')),
                ('stockSustrato', models.IntegerField(default=0, verbose_name='Stock de Sustrato')),
                ('precioSustrato', models.IntegerField(default=0, verbose_name='Precio de Sustrato')),
                ('imagenSustrato', models.CharField(max_length=300, verbose_name='Imagen Sustrato')),
            ],
        ),
    ]
