# Generated by Django 3.1 on 2022-06-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220607_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustrato',
            name='stockSustrato',
            field=models.IntegerField(default=0, verbose_name='Stock de Sustrato'),
        ),
    ]
