# Generated by Django 3.1 on 2022-06-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sustrato_stocksustrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=0, max_length=300, verbose_name='Dirección'),
            preserve_default=False,
        ),
    ]
