# Generated by Django 3.1 on 2022-06-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='flor',
            name='stockFlor',
            field=models.IntegerField(default=0, verbose_name='Stock de Flores'),
        ),
        migrations.AlterField(
            model_name='sustrato',
            name='tipoSustrato',
            field=models.CharField(max_length=50, verbose_name='Tipo de Sustrato'),
        ),
    ]
