# Generated by Django 3.1 on 2022-06-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220607_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbusto',
            name='precioArbusto',
            field=models.IntegerField(default=0, verbose_name='Precio de Arbusto'),
        ),
        migrations.AddField(
            model_name='arbusto',
            name='stockArbusto',
            field=models.IntegerField(default=0, verbose_name='Stock de Arbusto'),
        ),
        migrations.AddField(
            model_name='flor',
            name='precioFlor',
            field=models.IntegerField(default=0, verbose_name='Precio de Flor'),
        ),
        migrations.AddField(
            model_name='sustrato',
            name='precioSustrato',
            field=models.IntegerField(default=0, verbose_name='Precio de Sustrato'),
        ),
        migrations.AlterField(
            model_name='flor',
            name='stockFlor',
            field=models.IntegerField(default=0, verbose_name='Stock de Flor'),
        ),
    ]
