# Generated by Django 3.1 on 2022-06-07 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220607_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimaModificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
    ]
