# Generated by Django 3.1 on 2022-06-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_flor_imagenflor'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbusto',
            name='imagenArbusto',
            field=models.CharField(default=0, max_length=300, verbose_name='Imagen Arbusto'),
            preserve_default=False,
        ),
    ]
