# Generated by Django 3.1 on 2022-06-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_arbusto_imagenarbusto'),
    ]

    operations = [
        migrations.AddField(
            model_name='macetero',
            name='imagenMacetero',
            field=models.CharField(default=0, max_length=300, verbose_name='Imagen Macetero'),
            preserve_default=False,
        ),
    ]
