# Generated by Django 3.1 on 2022-06-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_macetero_imagenmacetero'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustrato',
            name='imagenSustrato',
            field=models.CharField(default=0, max_length=300, verbose_name='Imagen Sustrato'),
            preserve_default=False,
        ),
    ]
