# Generated by Django 3.1 on 2022-06-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sustrato_imagensustrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProd',
            fields=[
                ('idCategoria', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Id Categoría')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Categoría')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha modificación')),
            ],
        ),
    ]
