# Generated by Django 3.1 on 2022-06-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_categoriaprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaprod',
            name='idCategoria',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='Id Categoría'),
        ),
    ]
