# Generated by Django 3.1 on 2022-06-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220610_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaprod',
            name='idCategoria',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoría'),
        ),
    ]
