# Generated by Django 3.1 on 2022-06-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220610_0519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaProd',
        ),
    ]
