# Generated by Django 3.1 on 2022-06-10 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_auto_20220610_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de dirección')),
                ('direccionUno', models.CharField(max_length=300, verbose_name='Dirección 1')),
                ('direccionDos', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección 2')),
                ('direccionTres', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección 3')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.ManyToManyField(related_name='get_posts', to='core.Direccion', verbose_name='Dirección'),
        ),
    ]
