# Generated by Django 3.1 on 2022-06-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220610_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=False, max_length=300, verbose_name='Dirección'),
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
