# Generated by Django 3.1 on 2022-06-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20220610_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=300, verbose_name='Dirección'),
        ),
    ]
