# Generated by Django 3.1 on 2022-07-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20220610_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombreProducto', models.CharField(max_length=200, verbose_name='Nombre Producto')),
                ('tipoProducto', models.CharField(max_length=200, verbose_name='Tipo Producto')),
                ('precioProducto', models.FloatField()),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('imagenProducto', models.CharField(max_length=300, verbose_name='Imagen Producto')),
            ],
        ),
    ]
