# Generated by Django 3.1 on 2022-07-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
