# Generated by Django 3.1.12 on 2025-01-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_producto', '0002_direcciondespacho_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaccion_id',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
